[book]
title = "ForgeWare"
authors = ["Alejandro Morales", "Amanda Estevez, Ailen Morales"]
description = "Collection of resources and tools for implementing DevOps practices."

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/AleMorales9011/ForgeWare"
git-repository-icon = "fa-github"
